### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [FAXES/Fax-Core#11]
cfx> [     script:Fax-Core] SCRIPT ERROR: @Fax-Core/s_server.lua:77: bad argument #1 to 'find' (string expected, got nil)
[     script:Fax-Core] > userCallback (@Fax-Core/s_server.lua:77)

**Comment by Legacy-TacticalGamingInteractive** [comment]
[s_server.txt](https://github.com/FAXES/Fax-Core/files/7761147/s_server.txt)

**Comment by FAXES** [comment]
FaxCore is 5 years old now and I don't plan to update this due to time constraints I have nowadays. Sorry for the inconvenience with this.
