### ISSUE TITLE
dont delete vehicle, force to get out

### ISSUE THREAD

**Issue by Ultrunz** [FAXES/Fax-Core#5]
I'm not amazing at code, but this is what i have came up with. Although I have yet to implement it because I am a bit new to Lua. 

```
-- Functions for owners
function isCarBlacklistedowner(model)
	for _, blacklistedCar in pairs(ownercarblacklist) do
		if model == GetHashKey(blacklistedCar) then
			return true
		end
	end

	return false
end

function checkCarowner(car)
	if car then
		carModel = GetEntityModel(car)
		carName = GetDisplayNameFromVehicleModel(carModel)

	if isCarBlacklistedowner(carModel) then
		local player = PlayerPedId()
		local vehicle = GetVehiclePedIsIn(player, false)
		local flag = 16
		TaskLeaveVehicle(player, vehicle, flag)
		notifycar()
		end
	end
end
```

If anyone could point me in the right direction that'd be amazing.

**Comment by FAXES** [comment]
This is something I'm working on. I am essentially rewriting Fax-Core to work heaps better.

Please join my discord for more updates
http://faxes.zone/discord

**Comment by Ultrunz** [comment]
For a temporary fix would that code be worth implementing? Just want something for now while I wait for your new release :D

**Comment by Ultrunz** [comment]
Dude this works really well. Just been testing it out on mine :) Hope it helps you out too! :D

**Comment by Ultrunz** [comment]
So i just realised that I had only changed the first one, I went through and changed lines 22, 65, 108, 151, 194, 237 and 280 from

			`_DeleteEntity(car)`

to this

```
		local player = PlayerPedId()
		local vehicle = GetVehiclePedIsIn(player, false)
		local flag = 16
		TaskLeaveVehicle(player, vehicle, flag)
```

It is by no means a permanent fix. But it is decent enough to serve purpose till you release your newer reworked. Which I look forward to

**Comment by Ultrunz** [comment]
I'm not sure if it was my edits. But now I cannot put criminals in police cars

**Comment by Tommo-101** [comment]
This code won't work as it will force everyone who gets into the car without permission for that vehicle to get out. Needs a solution to only stop them from driving it.  This will also be why you cant put criminals into Police vehicles if they don't have permission to be in that vehicle.

**Comment by FAXES** [comment]
I have now added this
