### ISSUE TITLE
ERROR after joining

### ISSUE THREAD

**Issue by NebelRebell** [FAXES/Fax-Core#8]
Hello **at first thx for that fantastic scripts! - amazing** I use since today the Fax Core and installed it more times by reading wiki. I insert my steamIDHex and got after restart that error:

InvokeNative: execution failed: Argument at index 0 was null.
Error running system event handling function for resource Fax-Core: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: Execution of native 00000000dedae23d in script host failed.
stack traceback:

stack traceback:

What is wrong, please?

After restart fine:
https://media.discordapp.net/attachments/416213218516533250/589071334114590770/unknown.png

After Joining whoever:
https://media.discordapp.net/attachments/416213218516533250/589072687603777546/unknown.png

**Comment by FAXES** [comment]
FaxCore is 5 years old now and I don't plan to update this due to time constraints I have nowadays. Sorry for the inconvenience with this.
