### ISSUE TITLE
Error when player joins the server

### ISSUE THREAD

**Issue by Duqino** [FAXES/Fax-Core#9]
This happend not long ago. I think after server upgrade, but im not sure.

[![Screenshot from Gyazo](https://gyazo.com/12e3b92338e4b7b2c59cad8f5ee9493e/raw)](https://gyazo.com/12e3b92338e4b7b2c59cad8f5ee9493e)

**Comment by FAXES** [comment]
FaxCore is 5 years old now and I don't plan to update this due to time constraints I have nowadays. Sorry for the inconvenience with this.
